print("Ejercicio en clase")
print("-------------------------------------------------------------------")
v1=int(input("Ingrese un número entero:"))
v2=int(input("Ingrese un número entero:"))
v3=int(input("Ingrese un número entero:"))
v4=int(input("Ingrese un número entero:"))
v5=int(input("Ingrese un número entero:"))
v6=int(input("Ingrese un número entero:"))
v7=int(input("Ingrese un número entero:"))
v8=int(input("Ingrese un número entero:"))
v9=int(input("Ingrese un número entero:"))
v10=int(input("Ingrese un número entero:"))
print("-------------------------------------------------------------------")
l=[v1,v2,v3,v4,v5,v6,v7,v8,v9,v10]
print(l)
print("-------------------------------------------------------------------")
t1=(v1,v1**2)
print(t1)
t2=(v2,v2**2)
print(t2)
t3=(v3,v3**2)
print(t3)
t4=(v4,v4**2)
print(t4)
t5=(v5,v5**2)
print(t5)
t6=(v6,v6**2)
print(t6)
t7=(v7,v7**2)
print(t7)
t8=(v8,v8**2)
print(t8)
t9=(v9,v9**2)
print(t9)
t10=(v10,v10**2)
print(t10)
print("------------------------------------------------------------------")
l1=[t1,t2,t3,t4,t5,t6,t7,t8,t9,t10]
print(l1)
print("------------------------------------------------------------------")
sum=v1+v2+v3+v4+v5+v6+v7+v8+v9+v10
print("El resultado de la suma total de los datos es:",sum)
prom=sum//10
print("El promedio de la suma es:",prom)
dusm=sum*2
print("El doble de la suma es:",dusm)
print("------------------------------------------------------------------")
print("Otras operaciones")
op1=v1**v1
print(v1,"Con potencia de",v1,"es igual a:",op1)
op=v5/v4
print(v5,"Divido en",v4,"es igual a:",op)
op2=v10*v3
print(v10,"Multiplicado por",v3,"es igual a:",op2)
op3=v8**5
print(v8,"Con potencia de 5 es igual a:",op3)
op4=op3/v2
print(op3,"Divido en",v2,"es igual a:",op4)
print("----------------------------------------------------------------")
